name: Build and Deploy to GKE Staging
on:
  push:
    branches:
      - main
jobs:
  setup-build:
    name: Setup and Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"

      - run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
